apiVersion: v1
kind: Service
metadata:
  name: {{ include "jobflow.fullname" . }}-api-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "jobflow.name" . }}-api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
  type: ClusterIP
