apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jobflow.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "jobflow.fullname" . }}-postgres-service:5432/{{ .Values.postgres.database }}?schema=public"
  JWT_SECRET: "jobflow_prod_super_secret_jwt_key_at_least_32_bytes_long"
  REDIS_PASSWORD: ""
