apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jobflow.fullname" . }}-worker
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "jobflow.name" . }}-worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ include "jobflow.name" . }}-worker
  template:
    metadata:
      labels:
        app: {{ include "jobflow.name" . }}-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "dist/worker.js"]
          ports:
            - containerPort: {{ .Values.worker.port }}
              name: health-port
          envFrom:
            - configMapRef:
                name: {{ include "jobflow.fullname" . }}-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "jobflow.fullname" . }}-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "jobflow.fullname" . }}-secrets
                  key: JWT_SECRET
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "jobflow.fullname" . }}-secrets
                  key: REDIS_PASSWORD
            - name: OTEL_SERVICE_NAME
              value: "{{ include "jobflow.name" . }}-worker"
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /startup
              port: {{ .Values.worker.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.worker.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.worker.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
