apiVersion: v1
kind: Secret
metadata:
  name: jobflow-secrets
  namespace: jobflow
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgrespassword@postgres-service:5432/jobflow?schema=public"
  JWT_SECRET: "jobflow_prod_super_secret_jwt_key_at_least_32_bytes_long"
  REDIS_PASSWORD: ""
