export const WORKFLOW_EVENTS = {
  CREATED: 'WORKFLOW_CREATED',
  STARTED: 'WORKFLOW_STARTED',
  COMPLETED: 'WORKFLOW_COMPLETED',
  FAILED: 'WORKFLOW_FAILED',
  CANCELLED: 'WORKFLOW_CANCELLED',
  STEP_STARTED: 'STEP_STARTED',
  STEP_COMPLETED: 'STEP_COMPLETED',
  STEP_FAILED: 'STEP_FAILED',
  STEP_CANCELLED: 'STEP_CANCELLED',
};
